spool_size: 9000
idle_timeout: 180s
filebeat.inputs:
  - type: docker
    enabled: true
    containers.ids:
      - '*'
    ignore_older: 24h
    fields_under_root: true
    fields:
        rancher.environment: ##ENVIRONMENT##      
filebeat.autodiscover: ~
processors:
  - add_docker_metadata: ~
  - rename:
      fields:
        - from: "docker.container.labels.io.rancher.stack_service.name"
          to: "stack_service_container"
output.elasticsearch:
  username: ##USERNAME##
  password: ##PASSWORD##
  hosts: ["##PROTOCOL##://##HOSTURL##"]
